### ISSUE TITLE
The pre-trained model's Baidu Netdisk link is invalid.

### ISSUE THREAD

**Issue by msk7131** [Dominic-ZZ/Dehaze-YUVRDNet#1]
The pre-trained model's Baidu Netdisk link is invalid.

**Comment by Dominic-ZZ** [comment]
https://drive.google.com/file/d/1v4k1LzI7Ozo99D3N7SxBHf1iogRiCJEz/view?usp=sharing

**Comment by msk7131** [comment]
thanks
